### ISSUE TITLE
Add profile model

### ISSUE THREAD

**Issue by inglesp** [PyconUK/ironcage#13]
We'll want to gather information about:
* contact details
* demographics
* dietary preferences
* accessibility requirements
and probably lots of other things.

**Comment by meshy** [comment]
Should this be a `Profile` model with a `OneToOneField` to the default `User` model, or will this be a custom user model (Django 1.5+ style)?

If the latter, it might be worth holding off on https://github.com/PyconUK/ironcage/issues/1 because changing the user model in the database can be a little frustrating.

**Comment by inglesp** [comment]
As discussed in Slack, we'll go with a custom user model.
