### ISSUE TITLE
Payment view asks for "Zip code"

### ISSUE THREAD

**Issue by evildmp** [PyconUK/ironcage#53]
I thought this might be to do with using a US test payment card, but even with a UK card it still says "Zip".

**Comment by inglesp** [comment]
Stripe can apparently determine how to do [postal code field validation](https://stripe.com/docs/stripe.js#postal-code-formatting) based on the country of the card number, but I can't make it ask for a postcode rather than a zip code.

Gathering the cardholder's zip code is recommended as defence against fraudulent purchases, but given that we're not shipping physical products, the risk is low here.  As such, I'd be happy to turn off gathering the zip code.

**Comment by inglesp** [comment]
Fixed in https://github.com/PyconUK/ironcage/commit/b1d9d8b88fda33fb951c0864bc6075de9119280d.  (I'm not sure why this hasn't been closed automatically!)
